name: Release
on:
  push:
    tags:
    - "*.*.*"
jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@master
      with:
        go-version: "1.13"
    - name: install counterfeiter
      run: "go get github.com/maxbrunsfeld/counterfeiter"
    - uses: actions/checkout@master
    - name: add GOPATH/bin to PATH
      run: "export PATH=$PATH:$(go env GOPATH)/bin"
    - uses: docker://goreleaser/goreleaser
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        args: release
      if: success()
